#!/bin/bash

function check_status {
  if [ $? -eq 0 ]; then
    echo -e "[  \033[32mOK\033[0m  ]"
  else
    echo -e "[\033[31mFAILED\033[0m]"
    exit 1
  fi
}

echo -e -n " Running LaTeX 1............ "
latex annals-openmc.tex > /dev/null
check_status

echo -e -n " Running BibTeX............. "
bibtex annals-openmc.aux > /dev/null
check_status

echo -e -n " Running LaTeX 2............ "
latex annals-openmc.tex > /dev/null
check_status

echo -e -n " Running LaTeX 3............ "
latex annals-openmc.tex > /dev/null
check_status

echo -e -n " Running dvips.............. "
dvips -Ppdf annals-openmc.dvi > /dev/null 2>&1
check_status

echo -e -n " Running ps2pdf............. "
ps2pdf annals-openmc.ps annals-openmc.pdf > /dev/null
check_status
