#!/bin/bash

function check_status {
  if [ $? -eq 0 ]; then
    echo -e "[  \033[32mOK\033[0m  ]"
  else
    echo -e "[\033[31mFAILED\033[0m]"
    exit 1
  fi
}

echo -e -n " Running pdflatex 1......... "
pdflatex annals-openmc.tex > /dev/null
check_status

echo -e -n " Running BibTeX............. "
bibtex annals-openmc.aux > /dev/null
check_status

echo -e -n " Running pdflatex 2......... "
pdflatex annals-openmc.tex > /dev/null
check_status

echo -e -n " Running pdflatex 3......... "
pdflatex annals-openmc.tex > /dev/null
check_status
